# Copyright (C) 2014 Google Inc.
#
# This file is part of ycmd.
#
# ycmd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ycmd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ycmd.  If not, see <http://www.gnu.org/licenses/>.

import os
import ycm_core

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
'cc',
'-c',
'-funsigned-char',
'-Wall',
'-O9',
'-DLINUX',
'-DT_Watcom32=1',
'-DT_Win32=2',
'-DT_OS2=3',
'-DT_DOS32=4',
'-DTG_Console=1',
'-DTG_Win31=2',
'-DTG_Win95=3',
'-DTG_PM=4',
'-DTC_IX86=1',
'-DTC_ALPHA=2',
'-DTARGET_OS=T_Linux',
'-DTARGET_CPU=TC_',
'-DTARGET_GUI=TG_Console',
'-DPRODUKTION',
'-DHAFAS_MEMORY_MANAGEMENT_ERROR_HANDLING',
'-DKERNPLUSPLUS',
'-DRGR_TEST_SUITE',
'-fexceptions',
'-D_LARGEFILE_SOURCE',
'-D_LARGEFILE64_SOURCE',
'-D_FILE_OFFSET_BITS=64',
'-Wshift-negative-value',
'-Wno-format-overflow',
'-Wno-unused-result',
'-fno-common',
'-DENABLE_INFOMODUS',
'-DSOCKET_ENABLED',
'-DHAFAS_MEMORY_THREAD_SAFE',
'-DSTATISTIK',
'-Wdeclaration-after-statement',
'-DSTANDALONE',
'-m32',
'-o',
'/usr/include',
'/usr/local/include'
]
#flags = [
#'-Wall',
#'-Wextra',
#'-Werror',
#'-fexceptions',
#'-DNDEBUG',
## THIS IS IMPORTANT! Without a "-std=<something>" flag, clang won't know which
## language to use when compiling headers. So it will guess. Badly. So C++
## headers will be compiled as C headers. You don't want that so ALWAYS specify
## a "-std=<something>".
## For a C project, you would set this to something like 'c99' instead of
## 'c++11'.
#'-std=c++11',
## ...and the same thing goes for the magic -x option which specifies the
## language that the files to be compiled are written in. This is mostly
## relevant for c++ headers.
## For a C project, you would set this to 'c' instead of 'c++'.
#'-x',
#'c++',
#'-isystem',
#'/usr/include',
#'-isystem',
#'/usr/local/include',
#'-isystem',
#'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1',
#'-isystem',
#'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include',
#]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


# This is the entry point; this function is called by ycmd to produce flags for
# a file.
def FlagsForFile( filename, **kwargs ):
  if not database:
    return {
      'flags': flags,
      'include_paths_relative_to_dir': DirectoryOfThisScript()
    }

  compilation_info = GetCompilationInfoForFile( filename )
  if not compilation_info:
    return None

  # Bear in mind that compilation_info.compiler_flags_ does NOT return a
  # python list, but a "list-like" StringVec object.
  return {
    'flags': list( compilation_info.compiler_flags_ ),
    'include_paths_relative_to_dir': compilation_info.compiler_working_dir_
  }
