alias -g F='| fzf'
alias -g G='| rg'
alias -g J='| jq'
alias -g X='| xq'
alias -g Y='| yq'

alias ls='eza --group-directories-first --icons=always'
alias ld='eza --only-dirs --icons=always'
alias ll='eza --long --group --group-directories-first --time-style=long-iso --icons=always --git'
alias lr='ll --reverse'
alias la='ll --all'
alias lt='eza --recurse --tree --long --group --group-directories-first --time-style=long-iso --icons=always'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gcl='git clean -f'
alias gco='git co'
alias gd='git diff -u'
alias gfb='git fb'
alias gft='git ft'
alias gl='git lg'
alias glt='git lt'
alias gpl='git pull'
alias gps='git push'
alias gr='cd "$(git rev-parse --show-toplevel)"'
alias grb='git rollback'
alias gs='git st'
alias guc='git uncommit'
alias gus='git unstage'
alias gusm='git usm'

alias cma='chezmoi -v apply'
alias cmd='chezmoi diff'
alias cme='chezmoi edit'
alias cmg='cd "$(chezmoi source-path)"'
alias cmzsh='chezmoi edit $HOME/.zshrc'
alias cmali='chezmoi edit $HOME/.config/zsh/alias.zsh'
alias cmenv='chezmoi edit $HOME/.config/zsh/environment.zsh'
alias cmfnc='chezmoi edit $HOME/.config/zsh/functions.zsh'
alias cmomz='chezmoi edit $HOME/.config/zsh/oh-my-zsh.zsh'

alias bpt='bpytop'
alias cpwd='printf "%s" "$PWD" | xclip -selection clipboard'
alias fd='fd -H'
alias ln='ln -sfnv'
alias lzg='lazygit'
alias rmd='rm -rf'
alias rmj2='rms ".j2"'
alias scat='sops --decrypt'
alias vim='nvim'
